### ISSUE TITLE
./templates/train_data.json

### ISSUE THREAD

**Issue by whitesockcat** [UniModal4Reasoning/ChartVLM#1]
Excellent job.
Don't see ./templates/train_data.json 
Can you provide it?

**Comment by BOBrown** [comment]
hi @whitesockcat  please refer to https://github.com/UniModal4Reasoning/ChartVLM/blob/main/auxiliary_decoder/train/templates/train_data.json

**Comment by BOBrown** [comment]
@whitesockcat 

This issue will be closed due to prolonged inactivity. If further discussion is needed, please reopen this issue.
