### ISSUE TITLE
What is the encoder of this model? 

### ISSUE THREAD

**Issue by realwangjiahao** [UniModal4Reasoning/ChartVLM#14]
In this article, you said you use a pixel-level encoder, could you please tell me what is this encoder?

**Comment by Road2Redemption** [comment]
I think it is the default encoder from pix2struct

**Comment by renqiux0302** [comment]
Yes, we have fine-tuned the pre-trained encoder from P2S.

**Comment by realwangjiahao** [comment]
Thanks a lot
