### ISSUE TITLE
execution time

### ISSUE THREAD

**Issue by AymenDoc** [UniModal4Reasoning/ChartVLM#2]
Hello, 
for this command line
model = '${PATH_TO_PRETRAINED_MODEL}/ChartVLM/base/'  #${PATH_TO_PRETRAINED_MODEL}
which model, we need to provide ?
Also why the execution time is too high for one image ?

**Comment by renqiux0302** [comment]
Hi, please refer to `../ChartVLM-base` or `../ChartVLM-large` that contains `instruction_adapter`, `base_decoder` and `auxiliary_decoder`.
As for the execution time, most of the time is used to load the model. And the speed also depends on the device you utilized (we conduct inference task on one single A100).
Thanks for you issues and we will try to optimize overall execution time.
