### ISSUE TITLE
model = LlamaForCausalLM.from_pretrained

### ISSUE THREAD

**Issue by AymenDoc** [UniModal4Reasoning/ChartVLM#3]
Hi,
I've tested your model for the image description task and noticed that when loading the auxiliary decoder model, it consumes a significant amount of resources. For instance, when running it on Google Colab, the memory usage peaked at 27 GB of GPU memory.
Is this level of resource consumption normal? Do you have any insights into why it requires such a large amount of memory?
Thanks

**Comment by renqiux0302** [comment]
Yes, it is normal for the resource consumption because the auxiliary decoder model is 7B in ChartVLM-base.
And the memory usage of our inference experiment peaked at 40GB of one A100.

**Comment by BOBrown** [comment]
@AymenDoc 

This issue will be closed due to prolonged inactivity. If further discussion is needed, please reopen this issue.
