### ISSUE TITLE
Missing chart_train.json

### ISSUE THREAD

**Issue by ebrillat-aubay** [UniModal4Reasoning/ChartVLM#4]
Hello,

I don't see the chart_train.json needed in the data_preprocess_SimChart9K.py ligne 26. 

Can you provied it ?

Best regards,

**Comment by renqiux0302** [comment]
Hi, we have updated `data_preprocess_SimChart9K.py` and you can preprocess the original [SimChart9K](https://drive.google.com/file/d/1M_NA3sIJNwCUfqB1HH0p4lsnEm3NbvsI/view) directly.
The folder is organized as:
SimChart9K
├── png
├── table

**Comment by ebrillat-aubay** [comment]
Okay thank you very much !

**Comment by BOBrown** [comment]
@ebrillat-aubay 

This issue will be closed due to prolonged inactivity. If further discussion is needed, please reopen this issue.
