### ISSUE TITLE
Did you use gt reference for GPT_Score evalution?

### ISSUE THREAD

**Issue by zhangliang-04** [UniModal4Reasoning/ChartVLM#5]
Hi @BOBrown,

Thanks for your open sourcing! I find that when evaluating gpt_scores, you prompt the model to consider the ground truth summary or codes. However, it seems that the gts are not given to GPT in this [code](https://github.com/UniModal4Reasoning/ChartVLM/blob/main/eval/eval_sum_ChartX.py#L60) I'm confused about whether you use gt in this evaluation?

**Comment by renqiux0302** [comment]
Hi @zhangliang-04,

In `eval_sum_ChartX.py` , `eval_des_ChartX.py`  and  `eval_redrw_code_ChartX.py`, all the evaluations are label-free. You can just use the prompt we provided as criterion to evaluate such open-ended tasks without "GT" reference.

**Comment by zhangliang-04** [comment]
> Hi @zhangliang-04,
> 
> In `eval_sum_ChartX.py` , `eval_des_ChartX.py` and `eval_redrw_code_ChartX.py`, all the evaluations are label-free. You can just use the prompt we provided as criterion to evaluate such open-ended tasks without "GT" reference.

OK, thanks for your reply!
