### ISSUE TITLE
Inquiry about Chart2Text source

### ISSUE THREAD

**Issue by buckerF** [UniModal4Reasoning/ChartVLM#6]
Greetings,

I would like to understand whether the dataset Chart2Text was obtained by following the steps outlined in JasonObeid/Chart2Text or if it was obtained and processed differently, perhaps using the vis-nlp/Chart-to-text approach with datasets like pew and statista.

Could you kindly provide clarification on this matter? 

Best regards,

**Comment by renqiux0302** [comment]
Hi @buckerF,

We have supplemented `base_decoder/train/tools/data_preprocess/data_preprocess_chart2text.py` for Chart2Text which you can directly use for data preprocessing.

Note that Chart2Text is organized as:
```
Chart2Text
├── images
│   ├── matplot
|   ├── statista
|   ├── table
├── multiColumn
│   ├── matplot
|   ├── statista
|   ├── table
├── README.md
├── trainOriginalSummary.txt
```

Hope this helps.

**Comment by BOBrown** [comment]
@buckerF 

This issue will be closed due to prolonged inactivity. If further discussion is needed, please reopen this issue.
