### ISSUE TITLE
Clarification Request Regarding Data Formats in train_data.json

### ISSUE THREAD

**Issue by buckerF** [UniModal4Reasoning/ChartVLM#7]
Hello,

I am currently exploring the train_data.json file in the ChartVLM repository, specifically regarding the formats of different types of instructional data included.

While I noticed that the file outlines the format for QA data, it appears that other types of instructional data, such as CSV, summarization, and drawing codes, are not explicitly documented.

Could you kindly provide details on the formats for these additional types of instructional data?

Thank you for your attention to this matter.

Best regards,

**Comment by renqiux0302** [comment]
Hi @buckerF,

We have updated `auxiliary_decoder/train/templates/train_data.json` which cover all tasks trained in auxiliaty decoder currently. Note that SE task (CSV) is trained in base decoder.

Hope you find this useful.

**Comment by buckerF** [comment]
Thanks @renqiux0302 !
Furthermore, will the instruction data for training auxiliary_decoder be open-sourced? Alternatively, will the specific methodology for constructing instruction data based on the existing four datasets be made available?

**Comment by BOBrown** [comment]
@buckerF 

This issue will be closed due to prolonged inactivity. If further discussion is needed, please reopen this issue.
