### ISSUE TITLE
The charts are beautiful. What tools did you use to draw them?

### ISSUE THREAD

**Issue by jingjingjing-ding** [UniModal4Reasoning/ChartVLM#8]
![motivation](https://github.com/UniModal4Reasoning/ChartVLM/assets/120441512/c0212449-c196-47cb-bd3b-165e313c0bb9)

**Comment by renqiux0302** [comment]
Hi @HaileyFamo, 
Thanks for your appreaciation of our designed figure. We utilise the combination of **`AxGlygh`, `AxMath` and `Visio`** for figure plotting, as well as the logo for different chart types.

You can also communicate with us for more drawing details via email or other methods. We are happy to discuss any chart-related issue in this community.

**Comment by BOBrown** [comment]
@HaileyFamo 

This issue will be closed due to prolonged inactivity. If further discussion is needed, please reopen this issue.
